config/routes.rb
SunspotExample::Application.routes.draw do
  resources :products
  root 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base

  # --------- Validations --------- #

  validates :name, presence: true
  validates :description, presence: true
  validates :photo, presence: true

  # --------- Paperclip Image Upload --------- #

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "150x150>" }
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  # ---------  Elastic Search --------- #

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  mappings dynamic: 'false' do
    indexes :name, type: 'string'
    indexes :price, type: 'integer'
    indexes :description, type: 'text'
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]


  def index
    if params[:search].present?
      @products = Product.search(params[:search]).records.to_a
      # .records will return the Rails Active Record Objects rather than Elastic Search objects (return by .results method)
      # .to_a will convert those all objects into an array and will assign it to the @products instance variable. 
    else
      @products = Product.all
    end
  end

  def show
  end

  def new
    @product = Product.new
  end


  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
    def product_params
      params.require(:product).permit(:name, :price, :description, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : 'Products Catalog' %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">

        <%= yield %>
        <br>
        <%= javascript_include_tag "application" %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => 'required' %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description , :required => 'required' %>
  </div>
  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo , :required => 'required' %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'button' %>
  </div>
<% end %>

app/views/products/index.html.erb
<h3>Products</h3>

<div class="row">
<%= form_tag products_path, :method => :get do %>
    <div class="large-6 columns">
        <div class="row collapse">
            <div class="small-10 columns">
                <%= text_field_tag :search, params[:search] %>
            </div>
            <div class="small-2 columns">
                <%= submit_tag "Search", :name => nil, :class => "button postfix" %>
            </div>
        </div>
    </div>
<% end %>
</div>

<div class="row">
<% if @products.empty? %>
    <p>No products added to database</p>
<% else %>
    <ul>
      <% @products.each do |product| %>
          <li>
            <div class="row">
              <h4><%= link_to product.name, product %></h4>
              <p><%= number_to_currency(product.price) %></p>
            </div>
            <div class="row">
              <div class="small-3 columns"><%= image_tag product.photo.url(:thumb) %></div>
              <div class="small-9 columns"><%= product.description %></div>
            </div>
          </li>
          <hr>
      <% end %>
    </ul>
<% end %>

<br>

<%= link_to 'New Product', new_product_path, :class => 'button' %>
</div>

app/views/products/new.html.erb
<h3>Add product</h3>

<%= render 'form' %>

<%= link_to 'Home', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @product.photo.url(:medium) %>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Delete', @product, method: :delete %> |
<%= link_to 'Home', products_path %>